import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for XingAI Passive Income Idea (daily.xingai.app).",
  alternates: { canonical: "/legal/privacy" },
};

const updated = "2026-09-06";

export default function PrivacyPage() {
  return (
    <article className="legal">
      <div>
        <h1>Privacy Policy</h1>
        <p className="meta">Last updated: {updated}</p>
        <p>
          XingAI Passive Income Idea (“the Service”) helps you review leftover todos and triage inbox items.
          This policy describes what we collect when the product is live.
        </p>
        <h2>1. Data we may process</h2>
        <p>
          Account identity (e.g. Google OAuth email), app-owned todos, preference settings (locale,
          theme), and—if you connect Gmail—message metadata and content needed for triage and draft
          replies. OAuth tokens are stored only as needed to call Gmail APIs you authorize.
        </p>
        <h2>2. AI processing</h2>
        <p>
          Drafts and brief suggestions may be generated by third-party AI providers. Do not paste
          secrets into prompts. Review every draft before approving a send.
        </p>
        <h2>3. Cookies and local storage</h2>
        <p>
          We use local storage for locale and theme. Session cookies may be used for authentication
          when login ships.
        </p>
        <h2>4. Sharing</h2>
        <p>
          We do not sell personal data. Providers (hosting, auth, AI, email APIs) process data only to
          run the Service.
        </p>
        <h2>5. Retention</h2>
        <p>
          Todos and connected-mail caches are kept while your account is active or until you delete
          them. You can request deletion via contact@xingai.app.
        </p>
        <h2>6. Contact</h2>
        <p>
          <a href="mailto:contact@xingai.app">contact@xingai.app</a>
        </p>
      </div>

      <hr />

      <div lang="zh-Hans">
        <h1>隐私政策</h1>
        <p className="meta">最后更新：{updated}</p>
        <p>
          XingAI Passive Income Idea（“本服务”）帮助你查看结转待办与分拣收件箱。本文说明上线后可能处理的数据。
        </p>
        <h2>1. 可能处理的数据</h2>
        <p>
          账户身份（如 Google OAuth 邮箱）、应用内待办、偏好（语言/主题），以及连接 Gmail 后为分拣与草稿所需的邮件元数据与内容。OAuth 令牌仅在授权调用所需范围内保存。
        </p>
        <h2>2. AI 处理</h2>
        <p>草稿与简报建议可能由第三方 AI 生成。请勿把密钥粘贴进提示。发送前务必审阅草稿。</p>
        <h2>3. Cookie 与本地存储</h2>
        <p>语言与主题使用本地存储；登录上线后可能使用会话 Cookie。</p>
        <h2>4. 共享</h2>
        <p>我们不出售个人数据。托管、认证、AI、邮件 API 等供应商仅为运行服务处理数据。</p>
        <h2>5. 保留</h2>
        <p>待办与邮件缓存在账户有效期间保留，或直至你删除。可通过 contact@xingai.app 申请删除。</p>
        <h2>6. 联系</h2>
        <p>
          <a href="mailto:contact@xingai.app">contact@xingai.app</a>
        </p>
      </div>

      <hr />

      <div lang="ko">
        <h1>개인정보 처리방침</h1>
        <p className="meta">최종 업데이트: {updated}</p>
        <p>
          XingAI Passive Income Idea(“서비스”)는 이월 할 일과 받은편지함 분류를 돕습니다. 운영 시 수집할 수
          있는 데이터를 설명합니다.
        </p>
        <h2>1. 처리 가능 데이터</h2>
        <p>
          계정 신원(Google OAuth 이메일 등), 앱 소유 할 일, 언어/테마 설정, Gmail 연결 시 분류·초안에
          필요한 메일 메타데이터·본문. OAuth 토큰은 승인된 API 호출에 필요한 범위만 보관합니다.
        </p>
        <h2>2. AI 처리</h2>
        <p>초안과 브리프 제안은 제3자 AI로 생성될 수 있습니다. 비밀을 프롬프트에 넣지 마세요.</p>
        <h2>3. 쿠키·로컬 저장소</h2>
        <p>언어·테마는 로컬 저장소를 사용합니다. 로그인 도입 시 세션 쿠키가 쓰일 수 있습니다.</p>
        <h2>4. 공유</h2>
        <p>개인정보를 판매하지 않습니다. 호스팅·인증·AI·메일 API 제공자는 서비스 운영 목적으로만 처리합니다.</p>
        <h2>5. 보관</h2>
        <p>계정 활성 기간 또는 삭제 요청 시까지 보관합니다. contact@xingai.app 로 삭제 요청 가능.</p>
        <h2>6. 문의</h2>
        <p>
          <a href="mailto:contact@xingai.app">contact@xingai.app</a>
        </p>
      </div>

      <p className="meta" style={{ marginTop: "1.5rem" }}>
        <Link href="/legal/terms">Terms</Link>
        {" · "}
        <Link href="/legal/disclaimer">Disclaimer</Link>
      </p>
    </article>
  );
}
